# Generated by Django 4.2.5 on 2023-09-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_product_description_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products/%Y/%m/%d/'),
        ),
    ]
